/****************************************************************************
**
** Metadata for eloamComLib generated by dumpcpp from type library
** d:\Program Files (x86)\eloamCom_2.2\bin\eloamCom.dll
**
****************************************************************************/

#define QAX_DUMPCPP_ELOAMCOMLIB_NOINLINES
#include "eloamcomlib.h"

using namespace eloamComLib;

static const uint qt_meta_data_eloamComLib__EloamImage[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       37,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       24, 36, 

 // signals: signature, parameters, type, tag, flags
       48, 87, 109, 110, 5,
       111, 136, 141, 142, 5,
       143, 169, 184, 185, 5,

 // slots: signature, parameters, type, tag, flags
       186, 223, 244, 249, 9,
       250, 278, 286, 291, 9,
       292, 315, 320, 325, 9,
       326, 374, 412, 417, 9,
       418, 435, 442, 447, 9,
       448, 470, 479, 490, 9,
       491, 508, 514, 519, 9,
       520, 530, 531, 536, 9,
       537, 585, 611, 616, 9,
       617, 652, 672, 677, 9,
       678, 697, 706, 714, 9,
       715, 729, 730, 734, 9,
       735, 747, 748, 752, 9,
       753, 769, 778, 786, 9,
       787, 798, 799, 803, 9,
       804, 819, 820, 824, 9,
       825, 835, 836, 840, 9,
       841, 851, 852, 856, 9,
       857, 900, 925, 930, 9,
       931, 965, 977, 982, 9,
       983, 996, 1001, 1006, 9,
       1007, 1027, 1045, 1050, 9,
       1051, 1061, 1062, 1067, 9,
       1068, 1094, 1109, 1114, 9,
       1115, 1133, 1147, 1152, 9,
       1153, 1180, 1198, 1203, 9,
       1204, 1231, 1237, 1242, 9,
       1243, 1256, 1261, 1266, 9,
       1267, 1280, 1285, 1290, 9,
       1291, 1303, 1308, 1313, 9,
       1314, 1329, 1339, 1344, 9,
       1345, 1355, 1356, 1361, 9,
       1362, 1371, 1372, 1377, 9,
       1378, 1409, 1470, 1475, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamImage() {
    static const char stringdata0[] = {
    "eloamComLib::EloamImage\0"
    "Interface 0\0IEloamImage\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "AdaptivePrint(double,double,QString)\0width,height,printer\0"
    "bool\0\0AdaptivePrintByDPI(QString)\0printer\0bool\0\0AdaptiveThreshold(int)\0flag\0bool\0\0Blend(IDispatch*,IDispatch*,IDispatch*,int,int)\0pRectDest,pImage,pRectSrc,weight,flag\0bool\0\0Copy(IDispatch*)\0pImage\0bool\0"
    "\0CreateMemory(int,int)\0fmt,flag\0IDispatch*\0\0Crop(IDispatch*)\0pRect\0bool\0\0Destroy()\0\0bool\0\0DrawText(IDispatch*,int,int,QString,QColor,int)\0pFont,x,y,text,clr,weight\0bool\0\0DrawTextEx(int,QString,QColor,int)\0"
    "pos,text,clr,weight\0bool\0\0GetBase64(int,int)\0fmt,flag\0QString\0\0GetChannels()\0\0int\0\0GetHeight()\0\0int\0\0GetMD5(int,int)\0fmt,flag\0QString\0\0GetWidth()\0\0int\0\0GetWidthStep()\0\0int\0\0GetXDPI()\0\0int\0\0GetYDPI()\0\0int\0"
    "\0Print(double,double,double,double,QString)\0x,y,width,height,printer\0bool\0\0PrintByDPI(double,double,QString)\0x,y,printer\0bool\0\0Rectify(int)\0flag\0bool\0\0Resize(int,int,int)\0width,height,flag\0bool\0\0Reverse()\0"
    "\0bool\0\0Rotate(double,QColor,int)\0angle,clr,flag\0bool\0\0Save(QString,int)\0fileName,flag\0bool\0\0SaveToPDF(int,QString,int)\0fmt,fileName,flag\0bool\0\0SetDiscernRect(IDispatch*)\0pRect\0bool\0\0SetXDPI(int)\0xDPI\0bool\0"
    "\0SetYDPI(int)\0yDPI\0bool\0\0Smooth(int)\0flag\0bool\0\0Threshold(int)\0Threshold\0bool\0\0ToColor()\0\0bool\0\0ToGray()\0\0bool\0\0Whiten(int,int,double,int,int)\0flag,Threshold,autoThresholdRatio,aroundNum,lowestBrightness\0"
    "bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamImage::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamImage(),
//qt_meta_data_eloamComLib__EloamImage }
};

void *EloamImage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamImage()))
        return static_cast<void*>(const_cast<EloamImage*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamImage[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       37,    10, // methods
       1,    195, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       25, 64, 86, 87, 5,
       88, 113, 118, 119, 5,
       120, 146, 161, 162, 5,

 // slots: signature, parameters, type, tag, flags
       163, 200, 221, 226, 9,
       227, 255, 263, 268, 9,
       269, 292, 297, 302, 9,
       303, 351, 389, 394, 9,
       395, 412, 419, 424, 9,
       425, 447, 456, 467, 9,
       468, 485, 491, 496, 9,
       497, 507, 508, 513, 9,
       514, 562, 588, 593, 9,
       594, 629, 649, 654, 9,
       655, 674, 683, 691, 9,
       692, 706, 707, 711, 9,
       712, 724, 725, 729, 9,
       730, 746, 755, 763, 9,
       764, 775, 776, 780, 9,
       781, 796, 797, 801, 9,
       802, 812, 813, 817, 9,
       818, 828, 829, 833, 9,
       834, 877, 902, 907, 9,
       908, 942, 954, 959, 9,
       960, 973, 978, 983, 9,
       984, 1004, 1022, 1027, 9,
       1028, 1038, 1039, 1044, 9,
       1045, 1071, 1086, 1091, 9,
       1092, 1110, 1124, 1129, 9,
       1130, 1157, 1175, 1180, 9,
       1181, 1208, 1214, 1219, 9,
       1220, 1233, 1238, 1243, 9,
       1244, 1257, 1262, 1267, 9,
       1268, 1280, 1285, 1290, 9,
       1291, 1306, 1316, 1321, 9,
       1322, 1332, 1333, 1338, 9,
       1339, 1348, 1349, 1354, 9,
       1355, 1386, 1447, 1452, 9,

 // properties: name, type, flags
       1453, 1461, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamImage() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamImage\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "AdaptivePrint(double,double,QString)\0width,height,printer\0bool\0"
    "\0AdaptivePrintByDPI(QString)\0printer\0bool\0\0AdaptiveThreshold(int)\0flag\0bool\0\0Blend(IDispatch*,IDispatch*,IDispatch*,int,int)\0pRectDest,pImage,pRectSrc,weight,flag\0bool\0\0Copy(IDispatch*)\0pImage\0bool\0\0CreateMemory(int,int)\0"
    "fmt,flag\0IDispatch*\0\0Crop(IDispatch*)\0pRect\0bool\0\0Destroy()\0\0bool\0\0DrawText(IDispatch*,int,int,QString,QColor,int)\0pFont,x,y,text,clr,weight\0bool\0\0DrawTextEx(int,QString,QColor,int)\0pos,text,clr,weight\0"
    "bool\0\0GetBase64(int,int)\0fmt,flag\0QString\0\0GetChannels()\0\0int\0\0GetHeight()\0\0int\0\0GetMD5(int,int)\0fmt,flag\0QString\0\0GetWidth()\0\0int\0\0GetWidthStep()\0\0int\0\0GetXDPI()\0\0int\0\0GetYDPI()\0\0int\0\0Print(double,double,double,double,QString)\0"
    "x,y,width,height,printer\0bool\0\0PrintByDPI(double,double,QString)\0x,y,printer\0bool\0\0Rectify(int)\0flag\0bool\0\0Resize(int,int,int)\0width,height,flag\0bool\0\0Reverse()\0\0bool\0\0Rotate(double,QColor,int)\0angle,clr,flag\0"
    "bool\0\0Save(QString,int)\0fileName,flag\0bool\0\0SaveToPDF(int,QString,int)\0fmt,fileName,flag\0bool\0\0SetDiscernRect(IDispatch*)\0pRect\0bool\0\0SetXDPI(int)\0xDPI\0bool\0\0SetYDPI(int)\0yDPI\0bool\0\0Smooth(int)\0flag\0bool\0"
    "\0Threshold(int)\0Threshold\0bool\0\0ToColor()\0\0bool\0\0ToGray()\0\0bool\0\0Whiten(int,int,double,int,int)\0flag,Threshold,autoThresholdRatio,aroundNum,lowestBrightness\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamImage::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamImage(),
//qt_meta_data_eloamComLib__IEloamImage }
};

void *IEloamImage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamImage()))
        return static_cast<void*>(const_cast<IEloamImage*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamImageList[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       11,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       28, 40, 

 // signals: signature, parameters, type, tag, flags
       56, 95, 117, 118, 5,
       119, 144, 149, 150, 5,
       151, 177, 192, 193, 5,

 // slots: signature, parameters, type, tag, flags
       194, 210, 217, 222, 9,
       223, 231, 232, 237, 9,
       238, 249, 250, 254, 9,
       255, 269, 273, 284, 9,
       285, 308, 319, 324, 9,
       325, 337, 341, 346, 9,
       347, 365, 379, 384, 9,
       385, 412, 430, 435, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamImageList() {
    static const char stringdata0[] = {
    "eloamComLib::EloamImageList\0"
    "Interface 0\0IEloamImageList\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Add(IDispatch*)\0pImage\0bool\0\0Clear()\0"
    "\0bool\0\0GetCount()\0\0int\0\0GetImage(int)\0idx\0IDispatch*\0\0Insert(IDispatch*,int)\0pImage,pos\0bool\0\0Remove(int)\0idx\0bool\0\0Save(QString,int)\0fileName,flag\0bool\0\0SaveToPDF(int,QString,int)\0fmt,fileName,flag\0bool\0"
    "\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamImageList::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamImageList(),
//qt_meta_data_eloamComLib__EloamImageList }
};

void *EloamImageList::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamImageList()))
        return static_cast<void*>(const_cast<EloamImageList*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamImageList[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       11,    10, // methods
       1,    65, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       29, 68, 90, 91, 5,
       92, 117, 122, 123, 5,
       124, 150, 165, 166, 5,

 // slots: signature, parameters, type, tag, flags
       167, 183, 190, 195, 9,
       196, 204, 205, 210, 9,
       211, 222, 223, 227, 9,
       228, 242, 246, 257, 9,
       258, 281, 292, 297, 9,
       298, 310, 314, 319, 9,
       320, 338, 352, 357, 9,
       358, 385, 403, 408, 9,

 // properties: name, type, flags
       409, 417, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamImageList() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamImageList\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Add(IDispatch*)\0pImage\0bool\0\0Clear()\0\0bool\0\0GetCount()\0\0int\0\0GetImage(int)\0"
    "idx\0IDispatch*\0\0Insert(IDispatch*,int)\0pImage,pos\0bool\0\0Remove(int)\0idx\0bool\0\0Save(QString,int)\0fileName,flag\0bool\0\0SaveToPDF(int,QString,int)\0fmt,fileName,flag\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamImageList::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamImageList(),
//qt_meta_data_eloamComLib__IEloamImageList }
};

void *IEloamImageList::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamImageList()))
        return static_cast<void*>(const_cast<IEloamImageList*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamMemory[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       9,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       25, 37, 

 // signals: signature, parameters, type, tag, flags
       50, 89, 111, 112, 5,
       113, 138, 143, 144, 5,
       145, 171, 186, 187, 5,

 // slots: signature, parameters, type, tag, flags
       188, 205, 210, 221, 9,
       222, 232, 233, 238, 9,
       239, 251, 252, 260, 9,
       261, 270, 271, 279, 9,
       280, 292, 293, 301, 9,
       302, 316, 325, 330, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamMemory() {
    static const char stringdata0[] = {
    "eloamComLib::EloamMemory\0"
    "Interface 0\0IEloamMemory\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "CreateImage(int)\0flag\0IDispatch*\0\0Destroy()\0"
    "\0bool\0\0GetBase64()\0\0QString\0\0GetMD5()\0\0QString\0\0GetString()\0\0QString\0\0Save(QString)\0fileName\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamMemory::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamMemory(),
//qt_meta_data_eloamComLib__EloamMemory }
};

void *EloamMemory::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamMemory()))
        return static_cast<void*>(const_cast<EloamMemory*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamMemory[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       9,    10, // methods
       1,    55, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       26, 65, 87, 88, 5,
       89, 114, 119, 120, 5,
       121, 147, 162, 163, 5,

 // slots: signature, parameters, type, tag, flags
       164, 181, 186, 197, 9,
       198, 208, 209, 214, 9,
       215, 227, 228, 236, 9,
       237, 246, 247, 255, 9,
       256, 268, 269, 277, 9,
       278, 292, 301, 306, 9,

 // properties: name, type, flags
       307, 315, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamMemory() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamMemory\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "CreateImage(int)\0flag\0IDispatch*\0\0Destroy()\0\0bool\0\0GetBase64()\0"
    "\0QString\0\0GetMD5()\0\0QString\0\0GetString()\0\0QString\0\0Save(QString)\0fileName\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamMemory::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamMemory(),
//qt_meta_data_eloamComLib__IEloamMemory }
};

void *IEloamMemory::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamMemory()))
        return static_cast<void*>(const_cast<IEloamMemory*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamGlobal[] = {

 // content:
       1,       // revision
       0,       // classname
       2,    10, // classinfo
       127,    14, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       25, 43, 
       63, 75, 

 // signals: signature, parameters, type, tag, flags
       88, 112, 122, 123, 5,
       124, 136, 140, 141, 5,
       142, 165, 178, 179, 5,
       180, 192, 196, 197, 5,
       198, 216, 221, 222, 5,
       223, 249, 259, 260, 5,
       261, 274, 283, 284, 5,
       285, 301, 314, 315, 5,
       316, 334, 338, 339, 5,
       340, 354, 358, 359, 5,
       360, 378, 385, 386, 5,
       387, 426, 448, 449, 5,
       450, 475, 480, 481, 5,
       482, 508, 523, 524, 5,

 // slots: signature, parameters, type, tag, flags
       525, 561, 579, 583, 9,
       584, 624, 634, 638, 9,
       639, 661, 662, 670, 9,
       671, 692, 693, 697, 9,
       698, 723, 729, 737, 9,
       738, 754, 755, 766, 9,
       767, 789, 798, 809, 9,
       810, 829, 837, 842, 9,
       843, 862, 870, 881, 9,
       882, 902, 911, 922, 9,
       923, 948, 970, 981, 9,
       982, 1017, 1029, 1040, 9,
       1041, 1074, 1088, 1099, 9,
       1100, 1118, 1119, 1130, 9,
       1131, 1168, 1182, 1193, 9,
       1194, 1209, 1210, 1221, 9,
       1222, 1252, 1261, 1272, 9,
       1273, 1301, 1319, 1330, 9,
       1331, 1352, 1362, 1373, 9,
       1374, 1407, 1417, 1428, 9,
       1429, 1462, 1476, 1487, 9,
       1488, 1544, 1608, 1619, 9,
       1620, 1636, 1637, 1642, 9,
       1643, 1658, 1659, 1664, 9,
       1665, 1678, 1679, 1684, 9,
       1685, 1704, 1705, 1710, 9,
       1711, 1726, 1727, 1732, 9,
       1733, 1745, 1746, 1751, 9,
       1752, 1767, 1768, 1773, 9,
       1774, 1795, 1796, 1801, 9,
       1802, 1819, 1820, 1825, 9,
       1826, 1843, 1852, 1857, 9,
       1858, 1890, 1897, 1902, 9,
       1903, 1930, 1937, 1942, 9,
       1943, 1984, 2000, 2004, 9,
       2005, 2021, 2022, 2027, 9,
       2028, 2055, 2067, 2072, 9,
       2073, 2104, 2120, 2125, 9,
       2126, 2162, 2176, 2181, 9,
       2182, 2217, 2229, 2234, 9,
       2235, 2253, 2254, 2258, 9,
       2259, 2279, 2283, 2291, 9,
       2292, 2312, 2316, 2320, 9,
       2321, 2340, 2341, 2346, 9,
       2347, 2370, 2371, 2382, 9,
       2383, 2398, 2399, 2410, 9,
       2411, 2431, 2432, 2437, 9,
       2438, 2462, 2463, 2474, 9,
       2475, 2492, 2497, 2501, 9,
       2502, 2526, 2535, 2543, 9,
       2544, 2566, 2575, 2579, 9,
       2580, 2604, 2610, 2621, 9,
       2622, 2647, 2656, 2664, 9,
       2665, 2684, 2689, 2697, 9,
       2698, 2721, 2722, 2733, 9,
       2734, 2754, 2759, 2770, 9,
       2771, 2794, 2798, 2806, 9,
       2807, 2834, 2843, 2847, 9,
       2848, 2870, 2875, 2879, 9,
       2880, 2900, 2909, 2917, 9,
       2918, 2936, 2937, 2941, 9,
       2942, 2963, 2968, 2976, 9,
       2977, 2995, 2996, 3000, 9,
       3001, 3021, 3025, 3033, 9,
       3034, 3058, 3059, 3067, 9,
       3068, 3099, 3105, 3113, 9,
       3114, 3148, 3149, 3153, 9,
       3154, 3178, 3179, 3187, 9,
       3188, 3209, 3213, 3221, 9,
       3222, 3239, 3240, 3251, 9,
       3252, 3266, 3267, 3272, 9,
       3273, 3286, 3287, 3292, 9,
       3293, 3304, 3305, 3310, 9,
       3311, 3328, 3329, 3334, 9,
       3335, 3348, 3349, 3354, 9,
       3355, 3365, 3366, 3371, 9,
       3372, 3385, 3386, 3391, 9,
       3392, 3411, 3412, 3417, 9,
       3418, 3433, 3434, 3439, 9,
       3440, 3461, 3462, 3467, 9,
       3468, 3493, 3498, 3506, 9,
       3507, 3531, 3532, 3540, 9,
       3541, 3560, 3561, 3566, 9,
       3567, 3593, 3594, 3599, 9,
       3600, 3625, 3626, 3631, 9,
       3632, 3651, 3652, 3657, 9,
       3658, 3688, 3713, 3718, 9,
       3719, 3732, 3733, 3738, 9,
       3739, 3770, 3771, 3779, 9,
       3780, 3797, 3798, 3806, 9,
       3807, 3823, 3824, 3832, 9,
       3833, 3853, 3854, 3862, 9,
       3863, 3891, 3896, 3904, 9,
       3905, 3934, 3939, 3947, 9,
       3948, 3962, 3963, 3968, 9,
       3969, 3982, 3983, 3988, 9,
       3989, 4008, 4016, 4021, 9,
       4022, 4043, 4057, 4062, 9,
       4063, 4083, 4088, 4093, 9,
       4094, 4111, 4116, 4121, 9,
       4122, 4147, 4152, 4157, 9,
       4158, 4182, 4183, 4188, 9,
       4189, 4212, 4213, 4218, 9,
       4219, 4243, 4244, 4249, 9,
       4250, 4270, 4271, 4276, 9,
       4277, 4294, 4295, 4300, 9,
       4301, 4324, 4325, 4330, 9,
       4331, 4350, 4351, 4356, 9,
       4357, 4386, 4395, 4403, 9,
       4404, 4429, 4430, 4434, 9,
       4435, 4450, 4451, 4456, 9,
       4457, 4474, 4475, 4480, 9,
       4481, 4500, 4501, 4506, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamGlobal() {
    static const char stringdata0[] = {
    "eloamComLib::EloamGlobal\0"
    "Event Interface 1\0_IEloamGlobalEvents\0Interface 0\0IEloamGlobal\0"
    "Arrival(IDispatch*,int)\0pVideo,id\0\0\0Biokey(int)\0ret\0\0\0DevChange(int,int,int)\0type,idx,dbt\0\0\0IdCard(int)\0ret\0\0\0MagneticCard(int)\0type\0\0\0MoveDetec(IDispatch*,int)\0"
    "pVideo,id\0\0\0Ocr(int,int)\0flag,ret\0\0\0Reader(int,int)\0type,subtype\0\0\0ShenZhenTong(int)\0ret\0\0\0TemplOcr(int)\0ret\0\0\0Touch(IDispatch*)\0pVideo\0\0\0exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0"
    "propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "BiokeyVerify(IDispatch*,IDispatch*)\0pMemory1,pMemory2\0int\0\0BiokeyVerifyFromString(QString,QString)\0str1,str2\0int\0\0CpuGetBankCardTrack()\0"
    "\0QString\0\0CpuGetRecordNumber()\0\0int\0\0CpuGetankCardRecord(int)\0index\0QString\0\0CreatVideoCap()\0\0IDispatch*\0\0CreateDevice(int,int)\0type,idx\0IDispatch*\0\0CreateDir(QString)\0dirPath\0bool\0\0CreateFtp(QString)\0"
    "ftpPath\0IDispatch*\0\0CreateHttp(QString)\0httpPath\0IDispatch*\0\0CreateImage(int,int,int)\0width,height,channels\0IDispatch*\0\0CreateImageFromBase64(QString,int)\0base64,flag\0IDispatch*\0\0CreateImageFromFile(QString,int)\0"
    "fileName,flag\0IDispatch*\0\0CreateImageList()\0\0IDispatch*\0\0CreateImageListFromFile(QString,int)\0fileName,flag\0IDispatch*\0\0CreateMemory()\0\0IDispatch*\0\0CreateMemoryFromFile(QString)\0fileName\0IDispatch*\0\0CreateRect(int,int,int,int)\0"
    "x,y,xwidth,height\0IDispatch*\0\0CreateTempl(QString)\0templName\0IDispatch*\0\0CreateTemplFromData(QString,int)\0data,flag\0IDispatch*\0\0CreateTemplFromFile(QString,int)\0fileName,flag\0IDispatch*\0\0CreateTypeface(int,int,int,int,int,int,int,int,QString)\0"
    "height,width,escap,orien,thickness,italic,underline,strike,font\0IDispatch*\0\0DeinitBarcode()\0\0bool\0\0DeinitBiokey()\0\0bool\0\0DeinitDevs()\0\0bool\0\0DeinitFaceDetect()\0\0bool\0\0DeinitIdCard()\0\0bool\0\0DeinitOcr()\0"
    "\0bool\0\0DeinitReader()\0\0bool\0\0DeinitShenZhenTong()\0\0bool\0\0DeinitTemplOcr()\0\0bool\0\0DelFile(QString)\0fileName\0bool\0\0DisableFaceRectCrop(IDispatch*)\0pVideo\0bool\0\0DiscernBarcode(IDispatch*)\0pImage\0bool\0\0DiscernFaceDetect(IDispatch*,IDispatch*)\0"
    "pImage1,pImage2\0int\0\0DiscernIdCard()\0\0bool\0\0DiscernOcr(int,IDispatch*)\0flag,pImage\0bool\0\0DiscernOcrList(int,IDispatch*)\0flag,pImageList\0bool\0\0DiscernTempl(IDispatch*,IDispatch*)\0pImage,pTempl\0bool\0\0EnableFaceRectCrop(IDispatch*,int)\0"
    "pVideo,flag\0bool\0\0GetBarcodeCount()\0\0int\0\0GetBarcodeData(int)\0idx\0QString\0\0GetBarcodeType(int)\0idx\0int\0\0GetBiokeyFeature()\0\0bool\0\0GetBiokeyFeatureData()\0\0IDispatch*\0\0GetBiokeyImg()\0\0IDispatch*\0\0GetBiokeyTemplate()\0"
    "\0bool\0\0GetBiokeyTemplateData()\0\0IDispatch*\0\0GetDevCount(int)\0type\0int\0\0GetDisplayName(int,int)\0type,idx\0QString\0\0GetEloamType(int,int)\0type,idx\0int\0\0GetFaceRect(IDispatch*)\0image\0IDispatch*\0\0GetFriendlyName(int,int)\0"
    "type,idx\0QString\0\0GetIdCardData(int)\0flag\0QString\0\0GetIdCardFingerprint()\0\0IDispatch*\0\0GetIdCardImage(int)\0flag\0IDispatch*\0\0GetKeyFromSoftDog(int)\0len\0QString\0\0GetOcrBarcodeType(int,int)\0page,blk\0int\0\0"
    "GetOcrBlockCount(int)\0page\0int\0\0GetOcrData(int,int)\0page,blk\0QString\0\0GetOcrPageCount()\0\0int\0\0GetOcrPlainText(int)\0page\0QString\0\0GetPrinterCount()\0\0int\0\0GetPrinterName(int)\0idx\0QString\0\0GetShenZhenTongAmount()\0"
    "\0QString\0\0GetShenZhenTongCardRecord(int)\0index\0QString\0\0GetShenZhenTongCardRecordNumber()\0\0int\0\0GetShenZhenTongNumber()\0\0QString\0\0GetTempName(QString)\0ext\0QString\0\0GetTemplResult()\0\0IDispatch*\0\0InitBarcode()\0"
    "\0bool\0\0InitBiokey()\0\0bool\0\0InitDevs()\0\0bool\0\0InitFaceDetect()\0\0bool\0\0InitIdCard()\0\0bool\0\0InitOcr()\0\0bool\0\0InitReader()\0\0bool\0\0InitShenZhenTong()\0\0bool\0\0InitTemplOcr()\0\0bool\0\0MagneticCardDeinit()\0\0bool\0"
    "\0MagneticCardGetData(int)\0type\0QString\0\0MagneticCardGetNumber()\0\0QString\0\0MagneticCardInit()\0\0bool\0\0MagneticCardReaderStart()\0\0bool\0\0MagneticCardReaderStop()\0\0bool\0\0PlayCaptureVoice()\0\0bool\0\0QuickOcr(QString,QString,int)\0"
    "filePath,resultPath,flag\0bool\0\0ReadIdCard()\0\0bool\0\0ReaderGetCpuCreditCardNumber()\0\0QString\0\0ReaderGetCpuId()\0\0QString\0\0ReaderGetM1Id()\0\0QString\0\0ReaderGetMemoryId()\0\0QString\0\0ReaderGetQuickPassData(int)\0"
    "type\0QString\0\0ReaderGetSocialCardData(int)\0type\0QString\0\0ReaderStart()\0\0bool\0\0ReaderStop()\0\0bool\0\0RemoveDir(QString)\0dirPath\0bool\0\0SaveOcr(QString,int)\0fileName,flag\0bool\0\0SetOcrLanguage(int)\0lang\0bool\0"
    "\0SetSoftDog(bool)\0open\0bool\0\0SetTemplOcrLanguage(int)\0lang\0bool\0\0StartShenZhenTongCard()\0\0bool\0\0StopGetBiokeyFeature()\0\0bool\0\0StopGetBiokeyTemplate()\0\0bool\0\0StopIdCardDiscern()\0\0bool\0\0StopOcrDiscern()\0"
    "\0bool\0\0StopShenZhenTongCard()\0\0bool\0\0StopTemplDiscern()\0\0bool\0\0VideoCapGetAudioDevName(int)\0devIndex\0QString\0\0VideoCapGetAudioDevNum()\0\0int\0\0VideoCapInit()\0\0bool\0\0WaitOcrDiscern()\0\0bool\0\0WaitTemplDiscern()\0"
    "\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamGlobal::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamGlobal(),
//qt_meta_data_eloamComLib__EloamGlobal }
};

void *EloamGlobal::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamGlobal()))
        return static_cast<void*>(const_cast<EloamGlobal*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamGlobal[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       116,    10, // methods
       1,    590, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       26, 65, 87, 88, 5,
       89, 114, 119, 120, 5,
       121, 147, 162, 163, 5,

 // slots: signature, parameters, type, tag, flags
       164, 200, 218, 222, 9,
       223, 263, 273, 277, 9,
       278, 300, 301, 309, 9,
       310, 331, 332, 336, 9,
       337, 362, 368, 376, 9,
       377, 393, 394, 405, 9,
       406, 428, 437, 448, 9,
       449, 468, 476, 481, 9,
       482, 501, 509, 520, 9,
       521, 541, 550, 561, 9,
       562, 587, 609, 620, 9,
       621, 656, 668, 679, 9,
       680, 713, 727, 738, 9,
       739, 757, 758, 769, 9,
       770, 807, 821, 832, 9,
       833, 848, 849, 860, 9,
       861, 891, 900, 911, 9,
       912, 940, 958, 969, 9,
       970, 991, 1001, 1012, 9,
       1013, 1046, 1056, 1067, 9,
       1068, 1101, 1115, 1126, 9,
       1127, 1183, 1247, 1258, 9,
       1259, 1275, 1276, 1281, 9,
       1282, 1297, 1298, 1303, 9,
       1304, 1317, 1318, 1323, 9,
       1324, 1343, 1344, 1349, 9,
       1350, 1365, 1366, 1371, 9,
       1372, 1384, 1385, 1390, 9,
       1391, 1406, 1407, 1412, 9,
       1413, 1434, 1435, 1440, 9,
       1441, 1458, 1459, 1464, 9,
       1465, 1482, 1491, 1496, 9,
       1497, 1529, 1536, 1541, 9,
       1542, 1569, 1576, 1581, 9,
       1582, 1623, 1639, 1643, 9,
       1644, 1660, 1661, 1666, 9,
       1667, 1694, 1706, 1711, 9,
       1712, 1743, 1759, 1764, 9,
       1765, 1801, 1815, 1820, 9,
       1821, 1856, 1868, 1873, 9,
       1874, 1892, 1893, 1897, 9,
       1898, 1918, 1922, 1930, 9,
       1931, 1951, 1955, 1959, 9,
       1960, 1979, 1980, 1985, 9,
       1986, 2009, 2010, 2021, 9,
       2022, 2037, 2038, 2049, 9,
       2050, 2070, 2071, 2076, 9,
       2077, 2101, 2102, 2113, 9,
       2114, 2131, 2136, 2140, 9,
       2141, 2165, 2174, 2182, 9,
       2183, 2205, 2214, 2218, 9,
       2219, 2243, 2249, 2260, 9,
       2261, 2286, 2295, 2303, 9,
       2304, 2323, 2328, 2336, 9,
       2337, 2360, 2361, 2372, 9,
       2373, 2393, 2398, 2409, 9,
       2410, 2433, 2437, 2445, 9,
       2446, 2473, 2482, 2486, 9,
       2487, 2509, 2514, 2518, 9,
       2519, 2539, 2548, 2556, 9,
       2557, 2575, 2576, 2580, 9,
       2581, 2602, 2607, 2615, 9,
       2616, 2634, 2635, 2639, 9,
       2640, 2660, 2664, 2672, 9,
       2673, 2697, 2698, 2706, 9,
       2707, 2738, 2744, 2752, 9,
       2753, 2787, 2788, 2792, 9,
       2793, 2817, 2818, 2826, 9,
       2827, 2848, 2852, 2860, 9,
       2861, 2878, 2879, 2890, 9,
       2891, 2905, 2906, 2911, 9,
       2912, 2925, 2926, 2931, 9,
       2932, 2943, 2944, 2949, 9,
       2950, 2967, 2968, 2973, 9,
       2974, 2987, 2988, 2993, 9,
       2994, 3004, 3005, 3010, 9,
       3011, 3024, 3025, 3030, 9,
       3031, 3050, 3051, 3056, 9,
       3057, 3072, 3073, 3078, 9,
       3079, 3100, 3101, 3106, 9,
       3107, 3132, 3137, 3145, 9,
       3146, 3170, 3171, 3179, 9,
       3180, 3199, 3200, 3205, 9,
       3206, 3232, 3233, 3238, 9,
       3239, 3264, 3265, 3270, 9,
       3271, 3290, 3291, 3296, 9,
       3297, 3327, 3352, 3357, 9,
       3358, 3371, 3372, 3377, 9,
       3378, 3409, 3410, 3418, 9,
       3419, 3436, 3437, 3445, 9,
       3446, 3462, 3463, 3471, 9,
       3472, 3492, 3493, 3501, 9,
       3502, 3530, 3535, 3543, 9,
       3544, 3573, 3578, 3586, 9,
       3587, 3601, 3602, 3607, 9,
       3608, 3621, 3622, 3627, 9,
       3628, 3647, 3655, 3660, 9,
       3661, 3682, 3696, 3701, 9,
       3702, 3722, 3727, 3732, 9,
       3733, 3750, 3755, 3760, 9,
       3761, 3786, 3791, 3796, 9,
       3797, 3821, 3822, 3827, 9,
       3828, 3851, 3852, 3857, 9,
       3858, 3882, 3883, 3888, 9,
       3889, 3909, 3910, 3915, 9,
       3916, 3933, 3934, 3939, 9,
       3940, 3963, 3964, 3969, 9,
       3970, 3989, 3990, 3995, 9,
       3996, 4025, 4034, 4042, 9,
       4043, 4068, 4069, 4073, 9,
       4074, 4089, 4090, 4095, 9,
       4096, 4113, 4114, 4119, 9,
       4120, 4139, 4140, 4145, 9,

 // properties: name, type, flags
       4146, 4154, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamGlobal() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamGlobal\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "BiokeyVerify(IDispatch*,IDispatch*)\0pMemory1,pMemory2\0int\0\0BiokeyVerifyFromString(QString,QString)\0"
    "str1,str2\0int\0\0CpuGetBankCardTrack()\0\0QString\0\0CpuGetRecordNumber()\0\0int\0\0CpuGetankCardRecord(int)\0index\0QString\0\0CreatVideoCap()\0\0IDispatch*\0\0CreateDevice(int,int)\0type,idx\0IDispatch*\0\0CreateDir(QString)\0"
    "dirPath\0bool\0\0CreateFtp(QString)\0ftpPath\0IDispatch*\0\0CreateHttp(QString)\0httpPath\0IDispatch*\0\0CreateImage(int,int,int)\0width,height,channels\0IDispatch*\0\0CreateImageFromBase64(QString,int)\0base64,flag\0IDispatch*\0"
    "\0CreateImageFromFile(QString,int)\0fileName,flag\0IDispatch*\0\0CreateImageList()\0\0IDispatch*\0\0CreateImageListFromFile(QString,int)\0fileName,flag\0IDispatch*\0\0CreateMemory()\0\0IDispatch*\0\0CreateMemoryFromFile(QString)\0"
    "fileName\0IDispatch*\0\0CreateRect(int,int,int,int)\0x,y,xwidth,height\0IDispatch*\0\0CreateTempl(QString)\0templName\0IDispatch*\0\0CreateTemplFromData(QString,int)\0data,flag\0IDispatch*\0\0CreateTemplFromFile(QString,int)\0"
    "fileName,flag\0IDispatch*\0\0CreateTypeface(int,int,int,int,int,int,int,int,QString)\0height,width,escap,orien,thickness,italic,underline,strike,font\0IDispatch*\0\0DeinitBarcode()\0\0bool\0\0DeinitBiokey()\0\0bool\0"
    "\0DeinitDevs()\0\0bool\0\0DeinitFaceDetect()\0\0bool\0\0DeinitIdCard()\0\0bool\0\0DeinitOcr()\0\0bool\0\0DeinitReader()\0\0bool\0\0DeinitShenZhenTong()\0\0bool\0\0DeinitTemplOcr()\0\0bool\0\0DelFile(QString)\0fileName\0bool\0\0DisableFaceRectCrop(IDispatch*)\0"
    "pVideo\0bool\0\0DiscernBarcode(IDispatch*)\0pImage\0bool\0\0DiscernFaceDetect(IDispatch*,IDispatch*)\0pImage1,pImage2\0int\0\0DiscernIdCard()\0\0bool\0\0DiscernOcr(int,IDispatch*)\0flag,pImage\0bool\0\0DiscernOcrList(int,IDispatch*)\0"
    "flag,pImageList\0bool\0\0DiscernTempl(IDispatch*,IDispatch*)\0pImage,pTempl\0bool\0\0EnableFaceRectCrop(IDispatch*,int)\0pVideo,flag\0bool\0\0GetBarcodeCount()\0\0int\0\0GetBarcodeData(int)\0idx\0QString\0\0GetBarcodeType(int)\0"
    "idx\0int\0\0GetBiokeyFeature()\0\0bool\0\0GetBiokeyFeatureData()\0\0IDispatch*\0\0GetBiokeyImg()\0\0IDispatch*\0\0GetBiokeyTemplate()\0\0bool\0\0GetBiokeyTemplateData()\0\0IDispatch*\0\0GetDevCount(int)\0type\0int\0\0GetDisplayName(int,int)\0"
    "type,idx\0QString\0\0GetEloamType(int,int)\0type,idx\0int\0\0GetFaceRect(IDispatch*)\0image\0IDispatch*\0\0GetFriendlyName(int,int)\0type,idx\0QString\0\0GetIdCardData(int)\0flag\0QString\0\0GetIdCardFingerprint()\0\0IDispatch*\0"
    "\0GetIdCardImage(int)\0flag\0IDispatch*\0\0GetKeyFromSoftDog(int)\0len\0QString\0\0GetOcrBarcodeType(int,int)\0page,blk\0int\0\0GetOcrBlockCount(int)\0page\0int\0\0GetOcrData(int,int)\0page,blk\0QString\0\0GetOcrPageCount()\0"
    "\0int\0\0GetOcrPlainText(int)\0page\0QString\0\0GetPrinterCount()\0\0int\0\0GetPrinterName(int)\0idx\0QString\0\0GetShenZhenTongAmount()\0\0QString\0\0GetShenZhenTongCardRecord(int)\0index\0QString\0\0GetShenZhenTongCardRecordNumber()\0"
    "\0int\0\0GetShenZhenTongNumber()\0\0QString\0\0GetTempName(QString)\0ext\0QString\0\0GetTemplResult()\0\0IDispatch*\0\0InitBarcode()\0\0bool\0\0InitBiokey()\0\0bool\0\0InitDevs()\0\0bool\0\0InitFaceDetect()\0\0bool\0\0InitIdCard()\0\0"
    "bool\0\0InitOcr()\0\0bool\0\0InitReader()\0\0bool\0\0InitShenZhenTong()\0\0bool\0\0InitTemplOcr()\0\0bool\0\0MagneticCardDeinit()\0\0bool\0\0MagneticCardGetData(int)\0type\0QString\0\0MagneticCardGetNumber()\0\0QString\0\0MagneticCardInit()\0"
    "\0bool\0\0MagneticCardReaderStart()\0\0bool\0\0MagneticCardReaderStop()\0\0bool\0\0PlayCaptureVoice()\0\0bool\0\0QuickOcr(QString,QString,int)\0filePath,resultPath,flag\0bool\0\0ReadIdCard()\0\0bool\0\0ReaderGetCpuCreditCardNumber()\0"
    "\0QString\0\0ReaderGetCpuId()\0\0QString\0\0ReaderGetM1Id()\0\0QString\0\0ReaderGetMemoryId()\0\0QString\0\0ReaderGetQuickPassData(int)\0type\0QString\0\0ReaderGetSocialCardData(int)\0type\0QString\0\0ReaderStart()\0\0bool\0\0ReaderStop()\0"
    "\0bool\0\0RemoveDir(QString)\0dirPath\0bool\0\0SaveOcr(QString,int)\0fileName,flag\0bool\0\0SetOcrLanguage(int)\0lang\0bool\0\0SetSoftDog(bool)\0open\0bool\0\0SetTemplOcrLanguage(int)\0lang\0bool\0\0StartShenZhenTongCard()\0\0"
    "bool\0\0StopGetBiokeyFeature()\0\0bool\0\0StopGetBiokeyTemplate()\0\0bool\0\0StopIdCardDiscern()\0\0bool\0\0StopOcrDiscern()\0\0bool\0\0StopShenZhenTongCard()\0\0bool\0\0StopTemplDiscern()\0\0bool\0\0VideoCapGetAudioDevName(int)\0"
    "devIndex\0QString\0\0VideoCapGetAudioDevNum()\0\0int\0\0VideoCapInit()\0\0bool\0\0WaitOcrDiscern()\0\0bool\0\0WaitTemplDiscern()\0\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamGlobal::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamGlobal(),
//qt_meta_data_eloamComLib__IEloamGlobal }
};

void *IEloamGlobal::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamGlobal()))
        return static_cast<void*>(const_cast<IEloamGlobal*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamDevice[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       27,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       25, 37, 

 // signals: signature, parameters, type, tag, flags
       50, 89, 111, 112, 5,
       113, 138, 143, 144, 5,
       145, 171, 186, 187, 5,

 // slots: signature, parameters, type, tag, flags
       188, 209, 228, 239, 9,
       240, 250, 251, 256, 9,
       257, 283, 294, 298, 9,
       299, 316, 317, 325, 9,
       326, 341, 342, 346, 9,
       347, 365, 366, 374, 9,
       375, 386, 387, 391, 9,
       392, 413, 414, 418, 9,
       419, 445, 453, 457, 9,
       458, 483, 487, 491, 9,
       492, 523, 535, 539, 9,
       540, 564, 568, 572, 9,
       573, 603, 615, 619, 9,
       620, 634, 635, 639, 9,
       640, 663, 664, 672, 9,
       673, 684, 685, 689, 9,
       690, 703, 704, 708, 9,
       709, 719, 720, 724, 9,
       725, 750, 761, 765, 9,
       766, 781, 782, 787, 9,
       788, 804, 805, 810, 9,
       811, 842, 860, 865, 9,
       866, 896, 914, 919, 9,
       920, 945, 951, 956, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamDevice() {
    static const char stringdata0[] = {
    "eloamComLib::EloamDevice\0"
    "Interface 0\0IEloamDevice\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "CreateVideo(int,int)\0resolution,subtype\0"
    "IDispatch*\0\0Destroy()\0\0bool\0\0GetCameraControl(int,int)\0prop,value\0int\0\0GetDisplayName()\0\0QString\0\0GetEloamType()\0\0int\0\0GetFriendlyName()\0\0QString\0\0GetIndex()\0\0int\0\0GetResolutionCount()\0\0int\0\0GetResolutionCountEx(int)\0"
    "subtype\0int\0\0GetResolutionHeight(int)\0idx\0int\0\0GetResolutionHeightEx(int,int)\0subtype,idx\0int\0\0GetResolutionWidth(int)\0idx\0int\0\0GetResolutionWidthEx(int,int)\0subtype,idx\0int\0\0GetScanSize()\0\0int\0\0GetSonixSerialNumber()\0"
    "\0QString\0\0GetState()\0\0int\0\0GetSubtype()\0\0int\0\0GetType()\0\0int\0\0GetVideoProcAmp(int,int)\0prop,value\0int\0\0PausePreview()\0\0bool\0\0ResumePreivew()\0\0bool\0\0SetCameraControl(int,int,bool)\0prop,value,isAuto\0bool\0"
    "\0SetVideoProcAmp(int,int,bool)\0prop,value,isAuto\0bool\0\0ShowProperty(IDispatch*)\0pView\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamDevice::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamDevice(),
//qt_meta_data_eloamComLib__EloamDevice }
};

void *EloamDevice::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamDevice()))
        return static_cast<void*>(const_cast<EloamDevice*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamDevice[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       27,    10, // methods
       1,    145, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       26, 65, 87, 88, 5,
       89, 114, 119, 120, 5,
       121, 147, 162, 163, 5,

 // slots: signature, parameters, type, tag, flags
       164, 185, 204, 215, 9,
       216, 226, 227, 232, 9,
       233, 259, 270, 274, 9,
       275, 292, 293, 301, 9,
       302, 317, 318, 322, 9,
       323, 341, 342, 350, 9,
       351, 362, 363, 367, 9,
       368, 389, 390, 394, 9,
       395, 421, 429, 433, 9,
       434, 459, 463, 467, 9,
       468, 499, 511, 515, 9,
       516, 540, 544, 548, 9,
       549, 579, 591, 595, 9,
       596, 610, 611, 615, 9,
       616, 639, 640, 648, 9,
       649, 660, 661, 665, 9,
       666, 679, 680, 684, 9,
       685, 695, 696, 700, 9,
       701, 726, 737, 741, 9,
       742, 757, 758, 763, 9,
       764, 780, 781, 786, 9,
       787, 818, 836, 841, 9,
       842, 872, 890, 895, 9,
       896, 921, 927, 932, 9,

 // properties: name, type, flags
       933, 941, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamDevice() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamDevice\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "CreateVideo(int,int)\0resolution,subtype\0IDispatch*\0\0Destroy()\0\0"
    "bool\0\0GetCameraControl(int,int)\0prop,value\0int\0\0GetDisplayName()\0\0QString\0\0GetEloamType()\0\0int\0\0GetFriendlyName()\0\0QString\0\0GetIndex()\0\0int\0\0GetResolutionCount()\0\0int\0\0GetResolutionCountEx(int)\0subtype\0"
    "int\0\0GetResolutionHeight(int)\0idx\0int\0\0GetResolutionHeightEx(int,int)\0subtype,idx\0int\0\0GetResolutionWidth(int)\0idx\0int\0\0GetResolutionWidthEx(int,int)\0subtype,idx\0int\0\0GetScanSize()\0\0int\0\0GetSonixSerialNumber()\0"
    "\0QString\0\0GetState()\0\0int\0\0GetSubtype()\0\0int\0\0GetType()\0\0int\0\0GetVideoProcAmp(int,int)\0prop,value\0int\0\0PausePreview()\0\0bool\0\0ResumePreivew()\0\0bool\0\0SetCameraControl(int,int,bool)\0prop,value,isAuto\0bool\0"
    "\0SetVideoProcAmp(int,int,bool)\0prop,value,isAuto\0bool\0\0ShowProperty(IDispatch*)\0pView\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamDevice::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamDevice(),
//qt_meta_data_eloamComLib__IEloamDevice }
};

void *IEloamDevice::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamDevice()))
        return static_cast<void*>(const_cast<IEloamDevice*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamHttp[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       12,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       23, 35, 

 // signals: signature, parameters, type, tag, flags
       46, 85, 107, 108, 5,
       109, 134, 139, 140, 5,
       141, 167, 182, 183, 5,

 // slots: signature, parameters, type, tag, flags
       184, 194, 195, 200, 9,
       201, 217, 218, 226, 9,
       227, 240, 241, 246, 9,
       247, 291, 331, 336, 9,
       337, 377, 404, 409, 9,
       410, 443, 463, 468, 9,
       469, 507, 526, 531, 9,
       532, 585, 623, 628, 9,
       629, 642, 643, 648, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamHttp() {
    static const char stringdata0[] = {
    "eloamComLib::EloamHttp\0"
    "Interface 0\0IEloamHttp\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Destroy()\0\0bool\0\0GetServerInfo()\0\0QString\0"
    "\0StopUpload()\0\0bool\0\0Upload(int,QString,QString,QString,QString)\0flag,localPath,headers,predata,taildata\0bool\0\0UploadImage(IDispatch*,int,int,QString)\0pImage,fmt,flag,remoteName\0bool\0\0UploadImageFile(QString,QString)\0"
    "fileName,remoteName\0bool\0\0UploadImageMemory(IDispatch*,QString)\0pMemory,remoteName\0bool\0\0UploadMemory(int,IDispatch*,QString,QString,QString)\0flag,pMemory,headers,predata,taildata\0bool\0\0WaitUpload()\0\0bool\0"
    "\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamHttp::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamHttp(),
//qt_meta_data_eloamComLib__EloamHttp }
};

void *EloamHttp::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamHttp()))
        return static_cast<void*>(const_cast<EloamHttp*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamHttp[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       12,    10, // methods
       1,    70, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       24, 63, 85, 86, 5,
       87, 112, 117, 118, 5,
       119, 145, 160, 161, 5,

 // slots: signature, parameters, type, tag, flags
       162, 172, 173, 178, 9,
       179, 195, 196, 204, 9,
       205, 218, 219, 224, 9,
       225, 269, 309, 314, 9,
       315, 355, 382, 387, 9,
       388, 421, 441, 446, 9,
       447, 485, 504, 509, 9,
       510, 563, 601, 606, 9,
       607, 620, 621, 626, 9,

 // properties: name, type, flags
       627, 635, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamHttp() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamHttp\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Destroy()\0\0bool\0\0GetServerInfo()\0\0QString\0\0StopUpload()\0\0bool\0\0"
    "Upload(int,QString,QString,QString,QString)\0flag,localPath,headers,predata,taildata\0bool\0\0UploadImage(IDispatch*,int,int,QString)\0pImage,fmt,flag,remoteName\0bool\0\0UploadImageFile(QString,QString)\0fileName,remoteName\0"
    "bool\0\0UploadImageMemory(IDispatch*,QString)\0pMemory,remoteName\0bool\0\0UploadMemory(int,IDispatch*,QString,QString,QString)\0flag,pMemory,headers,predata,taildata\0bool\0\0WaitUpload()\0\0bool\0\0"
    "control\0QString\0"
    ""
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamHttp::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamHttp(),
//qt_meta_data_eloamComLib__IEloamHttp }
};

void *IEloamHttp::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamHttp()))
        return static_cast<void*>(const_cast<IEloamHttp*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamFtp[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       9,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       22, 34, 

 // signals: signature, parameters, type, tag, flags
       44, 83, 105, 106, 5,
       107, 132, 137, 138, 5,
       139, 165, 180, 181, 5,

 // slots: signature, parameters, type, tag, flags
       182, 201, 209, 214, 9,
       215, 225, 226, 231, 9,
       232, 251, 259, 264, 9,
       265, 278, 279, 284, 9,
       285, 313, 339, 344, 9,
       345, 358, 359, 364, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamFtp() {
    static const char stringdata0[] = {
    "eloamComLib::EloamFtp\0"
    "Interface 0\0IEloamFtp\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "CreateDir(QString)\0dirPath\0bool\0\0Destroy()\0"
    "\0bool\0\0RemoveDir(QString)\0dirPath\0bool\0\0StopUpload()\0\0bool\0\0Upload(int,QString,QString)\0flag,localPath,remotePath\0bool\0\0WaitUpload()\0\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamFtp::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamFtp(),
//qt_meta_data_eloamComLib__EloamFtp }
};

void *EloamFtp::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamFtp()))
        return static_cast<void*>(const_cast<EloamFtp*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamFtp[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       9,    10, // methods
       1,    55, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       23, 62, 84, 85, 5,
       86, 111, 116, 117, 5,
       118, 144, 159, 160, 5,

 // slots: signature, parameters, type, tag, flags
       161, 180, 188, 193, 9,
       194, 204, 205, 210, 9,
       211, 230, 238, 243, 9,
       244, 257, 258, 263, 9,
       264, 292, 318, 323, 9,
       324, 337, 338, 343, 9,

 // properties: name, type, flags
       344, 352, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamFtp() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamFtp\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "CreateDir(QString)\0dirPath\0bool\0\0Destroy()\0\0bool\0\0RemoveDir(QString)\0"
    "dirPath\0bool\0\0StopUpload()\0\0bool\0\0Upload(int,QString,QString)\0flag,localPath,remotePath\0bool\0\0WaitUpload()\0\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamFtp::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamFtp(),
//qt_meta_data_eloamComLib__IEloamFtp }
};

void *IEloamFtp::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamFtp()))
        return static_cast<void*>(const_cast<IEloamFtp*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamVideo[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       45,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       24, 36, 

 // signals: signature, parameters, type, tag, flags
       48, 87, 109, 110, 5,
       111, 136, 141, 142, 5,
       143, 169, 184, 185, 5,

 // slots: signature, parameters, type, tag, flags
       186, 201, 202, 213, 9,
       214, 242, 257, 268, 9,
       269, 301, 316, 327, 9,
       328, 338, 339, 344, 9,
       345, 372, 373, 378, 9,
       379, 396, 397, 402, 9,
       403, 417, 418, 423, 9,
       424, 444, 445, 450, 9,
       451, 467, 468, 473, 9,
       474, 488, 489, 494, 9,
       495, 514, 515, 520, 9,
       521, 538, 539, 544, 9,
       545, 561, 562, 567, 9,
       568, 587, 588, 593, 9,
       594, 623, 628, 633, 9,
       634, 687, 713, 718, 9,
       719, 759, 779, 784, 9,
       785, 827, 848, 853, 9,
       854, 883, 898, 903, 9,
       904, 926, 931, 936, 9,
       937, 955, 960, 965, 9,
       966, 986, 991, 996, 9,
       997, 1010, 1011, 1016, 9,
       1017, 1038, 1043, 1048, 9,
       1049, 1065, 1066, 1071, 9,
       1072, 1090, 1095, 1100, 9,
       1101, 1122, 1132, 1137, 9,
       1138, 1145, 1146, 1151, 9,
       1152, 1168, 1169, 1174, 9,
       1175, 1187, 1188, 1199, 9,
       1200, 1212, 1213, 1217, 9,
       1218, 1234, 1235, 1239, 9,
       1240, 1253, 1254, 1258, 9,
       1259, 1270, 1271, 1275, 9,
       1276, 1285, 1286, 1291, 9,
       1292, 1304, 1305, 1310, 9,
       1311, 1324, 1325, 1330, 9,
       1331, 1345, 1346, 1351, 9,
       1352, 1370, 1376, 1381, 9,
       1382, 1414, 1427, 1432, 9,
       1433, 1458, 1472, 1477, 9,
       1478, 1491, 1492, 1497, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamVideo() {
    static const char stringdata0[] = {
    "eloamComLib::EloamVideo\0"
    "Interface 0\0IEloamVideo\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "CaputreImage()\0\0IDispatch*\0\0CreateImage(int,IDispatch*)\0"
    "scanSize,pView\0IDispatch*\0\0CreateImageList(int,IDispatch*)\0scanSize,pView\0IDispatch*\0\0Destroy()\0\0bool\0\0DisableAdaptiveThreshold()\0\0bool\0\0DisableAddText()\0\0bool\0\0DisableDate()\0\0bool\0\0DisableDelBkColor()\0"
    "\0bool\0\0DisableDeskew()\0\0bool\0\0DisableGray()\0\0bool\0\0DisableMoveDetec()\0\0bool\0\0DisableReverse()\0\0bool\0\0DisableSmooth()\0\0bool\0\0DisableThreshold()\0\0bool\0\0EnableAdaptiveThreshold(int)\0flag\0bool\0\0EnableAddText(IDispatch*,int,int,QString,QColor,int)\0"
    "pFont,x,y,text,clr,weight\0bool\0\0EnableAddTextEx(int,QString,QColor,int)\0pos,text,clr,weight\0bool\0\0EnableDate(IDispatch*,int,int,QColor,int)\0pFont,x,y,clr,weight\0bool\0\0EnableDateEx(int,QColor,int)\0pos,clr,weight\0"
    "bool\0\0EnableDelBkColor(int)\0flag\0bool\0\0EnableDeskew(int)\0flag\0bool\0\0EnableDeskewEx(int)\0flag\0bool\0\0EnableGray()\0\0bool\0\0EnableMoveDetec(int)\0flag\0bool\0\0EnableReverse()\0\0bool\0\0EnableSmooth(int)\0flag\0bool\0"
    "\0EnableThreshold(int)\0Threshold\0bool\0\0Flip()\0\0bool\0\0FlipAndMirror()\0\0bool\0\0GetDevice()\0\0IDispatch*\0\0GetHeight()\0\0int\0\0GetResolution()\0\0int\0\0GetSubtype()\0\0int\0\0GetWidth()\0\0int\0\0Mirror()\0\0bool\0\0Rotate180()\0"
    "\0bool\0\0RotateLeft()\0\0bool\0\0RotateRight()\0\0bool\0\0SetCropState(int)\0state\0bool\0\0SetDisplayRect(IDispatch*,bool)\0pRect,enable\0bool\0\0StartRecord(QString,int)\0filePath,flag\0bool\0\0StopRecord()\0\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamVideo::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamVideo(),
//qt_meta_data_eloamComLib__EloamVideo }
};

void *EloamVideo::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamVideo()))
        return static_cast<void*>(const_cast<EloamVideo*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamVideo[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       45,    10, // methods
       1,    235, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       25, 64, 86, 87, 5,
       88, 113, 118, 119, 5,
       120, 146, 161, 162, 5,

 // slots: signature, parameters, type, tag, flags
       163, 178, 179, 190, 9,
       191, 219, 234, 245, 9,
       246, 278, 293, 304, 9,
       305, 315, 316, 321, 9,
       322, 349, 350, 355, 9,
       356, 373, 374, 379, 9,
       380, 394, 395, 400, 9,
       401, 421, 422, 427, 9,
       428, 444, 445, 450, 9,
       451, 465, 466, 471, 9,
       472, 491, 492, 497, 9,
       498, 515, 516, 521, 9,
       522, 538, 539, 544, 9,
       545, 564, 565, 570, 9,
       571, 600, 605, 610, 9,
       611, 664, 690, 695, 9,
       696, 736, 756, 761, 9,
       762, 804, 825, 830, 9,
       831, 860, 875, 880, 9,
       881, 903, 908, 913, 9,
       914, 932, 937, 942, 9,
       943, 963, 968, 973, 9,
       974, 987, 988, 993, 9,
       994, 1015, 1020, 1025, 9,
       1026, 1042, 1043, 1048, 9,
       1049, 1067, 1072, 1077, 9,
       1078, 1099, 1109, 1114, 9,
       1115, 1122, 1123, 1128, 9,
       1129, 1145, 1146, 1151, 9,
       1152, 1164, 1165, 1176, 9,
       1177, 1189, 1190, 1194, 9,
       1195, 1211, 1212, 1216, 9,
       1217, 1230, 1231, 1235, 9,
       1236, 1247, 1248, 1252, 9,
       1253, 1262, 1263, 1268, 9,
       1269, 1281, 1282, 1287, 9,
       1288, 1301, 1302, 1307, 9,
       1308, 1322, 1323, 1328, 9,
       1329, 1347, 1353, 1358, 9,
       1359, 1391, 1404, 1409, 9,
       1410, 1435, 1449, 1454, 9,
       1455, 1468, 1469, 1474, 9,

 // properties: name, type, flags
       1475, 1483, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamVideo() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamVideo\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "CaputreImage()\0\0IDispatch*\0\0CreateImage(int,IDispatch*)\0scanSize,pView\0"
    "IDispatch*\0\0CreateImageList(int,IDispatch*)\0scanSize,pView\0IDispatch*\0\0Destroy()\0\0bool\0\0DisableAdaptiveThreshold()\0\0bool\0\0DisableAddText()\0\0bool\0\0DisableDate()\0\0bool\0\0DisableDelBkColor()\0\0bool\0\0DisableDeskew()\0"
    "\0bool\0\0DisableGray()\0\0bool\0\0DisableMoveDetec()\0\0bool\0\0DisableReverse()\0\0bool\0\0DisableSmooth()\0\0bool\0\0DisableThreshold()\0\0bool\0\0EnableAdaptiveThreshold(int)\0flag\0bool\0\0EnableAddText(IDispatch*,int,int,QString,QColor,int)\0"
    "pFont,x,y,text,clr,weight\0bool\0\0EnableAddTextEx(int,QString,QColor,int)\0pos,text,clr,weight\0bool\0\0EnableDate(IDispatch*,int,int,QColor,int)\0pFont,x,y,clr,weight\0bool\0\0EnableDateEx(int,QColor,int)\0pos,clr,weight\0"
    "bool\0\0EnableDelBkColor(int)\0flag\0bool\0\0EnableDeskew(int)\0flag\0bool\0\0EnableDeskewEx(int)\0flag\0bool\0\0EnableGray()\0\0bool\0\0EnableMoveDetec(int)\0flag\0bool\0\0EnableReverse()\0\0bool\0\0EnableSmooth(int)\0flag\0bool\0"
    "\0EnableThreshold(int)\0Threshold\0bool\0\0Flip()\0\0bool\0\0FlipAndMirror()\0\0bool\0\0GetDevice()\0\0IDispatch*\0\0GetHeight()\0\0int\0\0GetResolution()\0\0int\0\0GetSubtype()\0\0int\0\0GetWidth()\0\0int\0\0Mirror()\0\0bool\0\0Rotate180()\0"
    "\0bool\0\0RotateLeft()\0\0bool\0\0RotateRight()\0\0bool\0\0SetCropState(int)\0state\0bool\0\0SetDisplayRect(IDispatch*,bool)\0pRect,enable\0bool\0\0StartRecord(QString,int)\0filePath,flag\0bool\0\0StopRecord()\0\0bool\0\0"
    "control\0"
    "QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamVideo::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamVideo(),
//qt_meta_data_eloamComLib__IEloamVideo }
};

void *IEloamVideo::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamVideo()))
        return static_cast<void*>(const_cast<IEloamVideo*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamView[] = {

 // content:
       1,       // revision
       0,       // classname
       2,    10, // classinfo
       26,    14, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       23, 41, 
       59, 71, 

 // signals: signature, parameters, type, tag, flags
       82, 125, 153, 154, 5,
       155, 180, 197, 198, 5,
       199, 238, 260, 261, 5,
       262, 287, 292, 293, 5,
       294, 320, 335, 336, 5,

 // slots: signature, parameters, type, tag, flags
       337, 379, 406, 411, 9,
       412, 428, 429, 440, 9,
       441, 452, 453, 457, 9,
       458, 468, 469, 480, 9,
       481, 501, 502, 507, 9,
       508, 532, 539, 544, 9,
       545, 558, 559, 564, 9,
       565, 589, 596, 601, 9,
       602, 613, 614, 619, 9,
       620, 639, 643, 648, 9,
       649, 662, 663, 668, 9,
       669, 689, 695, 700, 9,
       701, 715, 716, 721, 9,
       722, 736, 742, 747, 9,
       748, 798, 859, 864, 9,
       865, 879, 885, 890, 9,
       891, 917, 923, 928, 9,
       929, 943, 949, 954, 9,
       955, 979, 988, 993, 9,
       994, 1006, 1007, 1012, 9,
       1013, 1026, 1027, 1032, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamView() {
    static const char stringdata0[] = {
    "eloamComLib::EloamView\0"
    "Event Interface 1\0_IEloamViewEvents\0Interface 0\0IEloamView\0"
    "VideoAttach(IDispatch*,int,IDispatch*,int)\0pVideo,videoId,pView,viewId\0\0\0View(IDispatch*,int,int)\0pView,flag,value\0\0\0exception(int,QString,QString,QString)\0"
    "code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "DrawCustomRect(int,IDispatch*,int,QColor)\0flag,pRect,cWidth,boxColor\0bool\0\0GetSelectRect()\0\0IDispatch*\0"
    "\0GetState()\0\0int\0\0GetView()\0\0IDispatch*\0\0PlayCaptureEffect()\0\0bool\0\0SelectImage(IDispatch*)\0pImage\0bool\0\0SelectNull()\0\0bool\0\0SelectVideo(IDispatch*)\0pVideo\0bool\0\0SetAdapt()\0\0bool\0\0SetBkColor(QColor)\0clr\0"
    "bool\0\0SetCarpete()\0\0bool\0\0SetFullScreen(bool)\0bFull\0bool\0\0SetOriginal()\0\0bool\0\0SetRatio(int)\0ratio\0bool\0\0SetRectangleFormat(int,int,QColor,int,int,QColor)\0lineStyle,lineSize,lineColor,pointStyle,pointSize,pointColor\0"
    "bool\0\0SetScale(int)\0scale\0bool\0\0SetSelectRect(IDispatch*)\0pRect\0bool\0\0SetState(int)\0state\0bool\0\0SetText(QString,QColor)\0text,clr\0bool\0\0SetZoomIn()\0\0bool\0\0SetZoomOut()\0\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamView::staticMetaObject = {
//{ &QWidget::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamView(),
//qt_meta_data_eloamComLib__EloamView }
};

void *EloamView::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamView()))
        return static_cast<void*>(const_cast<EloamView*>(this));
    return QAxWidget::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamView[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       24,    10, // methods
       1,    130, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       24, 63, 85, 86, 5,
       87, 112, 117, 118, 5,
       119, 145, 160, 161, 5,

 // slots: signature, parameters, type, tag, flags
       162, 204, 231, 236, 9,
       237, 253, 254, 265, 9,
       266, 277, 278, 282, 9,
       283, 293, 294, 305, 9,
       306, 326, 327, 332, 9,
       333, 357, 364, 369, 9,
       370, 383, 384, 389, 9,
       390, 414, 421, 426, 9,
       427, 438, 439, 444, 9,
       445, 464, 468, 473, 9,
       474, 487, 488, 493, 9,
       494, 514, 520, 525, 9,
       526, 540, 541, 546, 9,
       547, 561, 567, 572, 9,
       573, 623, 684, 689, 9,
       690, 704, 710, 715, 9,
       716, 742, 748, 753, 9,
       754, 768, 774, 779, 9,
       780, 804, 813, 818, 9,
       819, 831, 832, 837, 9,
       838, 851, 852, 857, 9,

 // properties: name, type, flags
       858, 866, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamView() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamView\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "DrawCustomRect(int,IDispatch*,int,QColor)\0flag,pRect,cWidth,boxColor\0"
    "bool\0\0GetSelectRect()\0\0IDispatch*\0\0GetState()\0\0int\0\0GetView()\0\0IDispatch*\0\0PlayCaptureEffect()\0\0bool\0\0SelectImage(IDispatch*)\0pImage\0bool\0\0SelectNull()\0\0bool\0\0SelectVideo(IDispatch*)\0pVideo\0bool\0\0SetAdapt()\0"
    "\0bool\0\0SetBkColor(QColor)\0clr\0bool\0\0SetCarpete()\0\0bool\0\0SetFullScreen(bool)\0bFull\0bool\0\0SetOriginal()\0\0bool\0\0SetRatio(int)\0ratio\0bool\0\0SetRectangleFormat(int,int,QColor,int,int,QColor)\0lineStyle,lineSize,lineColor,pointStyle,pointSize,pointColor\0"
    "bool\0\0SetScale(int)\0scale\0bool\0\0SetSelectRect(IDispatch*)\0pRect\0bool\0\0SetState(int)\0state\0bool\0\0SetText(QString,QColor)\0text,clr\0bool\0\0SetZoomIn()\0\0bool\0\0SetZoomOut()\0\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamView::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamView(),
//qt_meta_data_eloamComLib__IEloamView }
};

void *IEloamView::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamView()))
        return static_cast<void*>(const_cast<IEloamView*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamThumbnail[] = {

 // content:
       1,       // revision
       0,       // classname
       2,    10, // classinfo
       17,    14, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       28, 46, 
       69, 81, 

 // signals: signature, parameters, type, tag, flags
       97, 136, 158, 159, 5,
       160, 185, 190, 191, 5,
       192, 218, 233, 234, 5,

 // slots: signature, parameters, type, tag, flags
       235, 248, 257, 262, 9,
       263, 275, 280, 285, 9,
       286, 300, 304, 309, 9,
       310, 321, 322, 326, 9,
       327, 344, 348, 356, 9,
       357, 377, 378, 386, 9,
       387, 401, 402, 406, 9,
       407, 422, 423, 434, 9,
       435, 469, 488, 493, 9,
       494, 514, 527, 532, 9,
       533, 550, 559, 564, 9,
       565, 584, 595, 600, 9,
       601, 618, 625, 630, 9,
       631, 652, 664, 669, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamThumbnail() {
    static const char stringdata0[] = {
    "eloamComLib::EloamThumbnail\0"
    "Event Interface 1\0_IEloamThumbnailEvents\0Interface 0\0IEloamThumbnail\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0"
    "\0\0"
    "Add(QString)\0fileName\0bool\0\0Clear(bool)\0bDel\0bool\0\0GetCheck(int)\0idx\0bool\0\0GetCount()\0\0int\0\0GetFileName(int)\0idx\0QString\0\0GetHttpServerInfo()\0\0QString\0\0GetSelected()\0\0int\0\0GetThumbnail()\0\0IDispatch*\0"
    "\0HttpUploadCheckImage(QString,int)\0serverAddress,flag\0bool\0\0Insert(QString,int)\0fileName,pos\0bool\0\0Remove(int,bool)\0idx,bDel\0bool\0\0SetCheck(int,bool)\0idx,bCheck\0bool\0\0SetLanguage(int)\0langId\0bool\0\0SetMenuItem(int,int)\0"
    "menuId,flag\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamThumbnail::staticMetaObject = {
//{ &QWidget::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamThumbnail(),
//qt_meta_data_eloamComLib__EloamThumbnail }
};

void *EloamThumbnail::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamThumbnail()))
        return static_cast<void*>(const_cast<EloamThumbnail*>(this));
    return QAxWidget::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamThumbnail[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       17,    10, // methods
       1,    95, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       29, 68, 90, 91, 5,
       92, 117, 122, 123, 5,
       124, 150, 165, 166, 5,

 // slots: signature, parameters, type, tag, flags
       167, 180, 189, 194, 9,
       195, 207, 212, 217, 9,
       218, 232, 236, 241, 9,
       242, 253, 254, 258, 9,
       259, 276, 280, 288, 9,
       289, 309, 310, 318, 9,
       319, 333, 334, 338, 9,
       339, 354, 355, 366, 9,
       367, 401, 420, 425, 9,
       426, 446, 459, 464, 9,
       465, 482, 491, 496, 9,
       497, 516, 527, 532, 9,
       533, 550, 557, 562, 9,
       563, 584, 596, 601, 9,

 // properties: name, type, flags
       602, 610, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamThumbnail() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamThumbnail\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Add(QString)\0fileName\0bool\0\0Clear(bool)\0bDel\0bool\0\0GetCheck(int)\0"
    "idx\0bool\0\0GetCount()\0\0int\0\0GetFileName(int)\0idx\0QString\0\0GetHttpServerInfo()\0\0QString\0\0GetSelected()\0\0int\0\0GetThumbnail()\0\0IDispatch*\0\0HttpUploadCheckImage(QString,int)\0serverAddress,flag\0bool\0\0Insert(QString,int)\0"
    "fileName,pos\0bool\0\0Remove(int,bool)\0idx,bDel\0bool\0\0SetCheck(int,bool)\0idx,bCheck\0bool\0\0SetLanguage(int)\0langId\0bool\0\0SetMenuItem(int,int)\0menuId,flag\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamThumbnail::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamThumbnail(),
//qt_meta_data_eloamComLib__IEloamThumbnail }
};

void *IEloamThumbnail::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamThumbnail()))
        return static_cast<void*>(const_cast<IEloamThumbnail*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamRect[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       13,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       23, 35, 

 // signals: signature, parameters, type, tag, flags
       46, 85, 107, 108, 5,
       109, 134, 139, 140, 5,
       141, 167, 182, 183, 5,

 // slots: signature, parameters, type, tag, flags
       184, 201, 207, 212, 9,
       213, 223, 224, 229, 9,
       230, 242, 243, 247, 9,
       248, 258, 259, 263, 9,
       264, 273, 274, 278, 9,
       279, 290, 291, 295, 9,
       296, 311, 318, 323, 9,
       324, 337, 342, 347, 9,
       348, 360, 364, 369, 9,
       370, 384, 390, 395, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamRect() {
    static const char stringdata0[] = {
    "eloamComLib::EloamRect\0"
    "Interface 0\0IEloamRect\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Copy(IDispatch*)\0pRect\0bool\0\0Destroy()\0\0"
    "bool\0\0GetHeight()\0\0int\0\0GetLeft()\0\0int\0\0GetTop()\0\0int\0\0GetWidth()\0\0int\0\0SetHeight(int)\0height\0bool\0\0SetLeft(int)\0left\0bool\0\0SetTop(int)\0top\0bool\0\0SetWidth(int)\0width\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamRect::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamRect(),
//qt_meta_data_eloamComLib__EloamRect }
};

void *EloamRect::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamRect()))
        return static_cast<void*>(const_cast<EloamRect*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamRect[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       13,    10, // methods
       1,    75, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       24, 63, 85, 86, 5,
       87, 112, 117, 118, 5,
       119, 145, 160, 161, 5,

 // slots: signature, parameters, type, tag, flags
       162, 179, 185, 190, 9,
       191, 201, 202, 207, 9,
       208, 220, 221, 225, 9,
       226, 236, 237, 241, 9,
       242, 251, 252, 256, 9,
       257, 268, 269, 273, 9,
       274, 289, 296, 301, 9,
       302, 315, 320, 325, 9,
       326, 338, 342, 347, 9,
       348, 362, 368, 373, 9,

 // properties: name, type, flags
       374, 382, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamRect() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamRect\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Copy(IDispatch*)\0pRect\0bool\0\0Destroy()\0\0bool\0\0GetHeight()\0\0int\0"
    "\0GetLeft()\0\0int\0\0GetTop()\0\0int\0\0GetWidth()\0\0int\0\0SetHeight(int)\0height\0bool\0\0SetLeft(int)\0left\0bool\0\0SetTop(int)\0top\0bool\0\0SetWidth(int)\0width\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamRect::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamRect(),
//qt_meta_data_eloamComLib__IEloamRect }
};

void *IEloamRect::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamRect()))
        return static_cast<void*>(const_cast<IEloamRect*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamFont[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       4,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       23, 35, 

 // signals: signature, parameters, type, tag, flags
       46, 85, 107, 108, 5,
       109, 134, 139, 140, 5,
       141, 167, 182, 183, 5,

 // slots: signature, parameters, type, tag, flags
       184, 194, 195, 200, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamFont() {
    static const char stringdata0[] = {
    "eloamComLib::EloamFont\0"
    "Interface 0\0IEloamFont\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Destroy()\0\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamFont::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamFont(),
//qt_meta_data_eloamComLib__EloamFont }
};

void *EloamFont::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamFont()))
        return static_cast<void*>(const_cast<EloamFont*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamFont[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       4,    10, // methods
       1,    30, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       24, 63, 85, 86, 5,
       87, 112, 117, 118, 5,
       119, 145, 160, 161, 5,

 // slots: signature, parameters, type, tag, flags
       162, 172, 173, 178, 9,

 // properties: name, type, flags
       179, 187, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamFont() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamFont\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Destroy()\0\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamFont::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamFont(),
//qt_meta_data_eloamComLib__IEloamFont }
};

void *IEloamFont::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamFont()))
        return static_cast<void*>(const_cast<IEloamFont*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamTempl[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       19,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       24, 36, 

 // signals: signature, parameters, type, tag, flags
       48, 87, 109, 110, 5,
       111, 136, 141, 142, 5,
       143, 169, 184, 185, 5,

 // slots: signature, parameters, type, tag, flags
       186, 239, 276, 281, 9,
       282, 295, 296, 301, 9,
       302, 312, 313, 318, 9,
       319, 332, 337, 345, 9,
       346, 362, 363, 367, 9,
       368, 386, 390, 398, 9,
       399, 423, 427, 434, 9,
       435, 457, 461, 468, 9,
       469, 492, 496, 503, 9,
       504, 525, 529, 536, 9,
       537, 557, 561, 569, 9,
       570, 588, 592, 596, 9,
       597, 605, 606, 614, 9,
       615, 625, 626, 634, 9,
       635, 653, 667, 672, 9,
       673, 701, 709, 714, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamTempl() {
    static const char stringdata0[] = {
    "eloamComLib::EloamTempl\0"
    "Interface 0\0IEloamTempl\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "AppendField(QString,int,double,double,double,double)\0"
    "fieldName,type,left,top,right,bottom\0bool\0\0ClearField()\0\0bool\0\0Destroy()\0\0bool\0\0GetData(int)\0flag\0QString\0\0GetFieldCount()\0\0int\0\0GetFieldName(int)\0idx\0QString\0\0GetFieldRectBottom(int)\0idx\0double\0\0GetFieldRectLeft(int)\0"
    "idx\0double\0\0GetFieldRectRight(int)\0idx\0double\0\0GetFieldRectTop(int)\0idx\0double\0\0GetFieldResult(int)\0idx\0QString\0\0GetFieldType(int)\0idx\0int\0\0GetId()\0\0QString\0\0GetName()\0\0QString\0\0Save(QString,int)\0fileName,flag\0"
    "bool\0\0SetFieldResult(int,QString)\0idx,res\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamTempl::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamTempl(),
//qt_meta_data_eloamComLib__EloamTempl }
};

void *EloamTempl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamTempl()))
        return static_cast<void*>(const_cast<EloamTempl*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamTempl[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       19,    10, // methods
       1,    105, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       25, 64, 86, 87, 5,
       88, 113, 118, 119, 5,
       120, 146, 161, 162, 5,

 // slots: signature, parameters, type, tag, flags
       163, 216, 253, 258, 9,
       259, 272, 273, 278, 9,
       279, 289, 290, 295, 9,
       296, 309, 314, 322, 9,
       323, 339, 340, 344, 9,
       345, 363, 367, 375, 9,
       376, 400, 404, 411, 9,
       412, 434, 438, 445, 9,
       446, 469, 473, 480, 9,
       481, 502, 506, 513, 9,
       514, 534, 538, 546, 9,
       547, 565, 569, 573, 9,
       574, 582, 583, 591, 9,
       592, 602, 603, 611, 9,
       612, 630, 644, 649, 9,
       650, 678, 686, 691, 9,

 // properties: name, type, flags
       692, 700, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamTempl() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamTempl\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "AppendField(QString,int,double,double,double,double)\0fieldName,type,left,top,right,bottom\0"
    "bool\0\0ClearField()\0\0bool\0\0Destroy()\0\0bool\0\0GetData(int)\0flag\0QString\0\0GetFieldCount()\0\0int\0\0GetFieldName(int)\0idx\0QString\0\0GetFieldRectBottom(int)\0idx\0double\0\0GetFieldRectLeft(int)\0idx\0double\0\0GetFieldRectRight(int)\0"
    "idx\0double\0\0GetFieldRectTop(int)\0idx\0double\0\0GetFieldResult(int)\0idx\0QString\0\0GetFieldType(int)\0idx\0int\0\0GetId()\0\0QString\0\0GetName()\0\0QString\0\0Save(QString,int)\0fileName,flag\0bool\0\0SetFieldResult(int,QString)\0"
    "idx,res\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamTempl::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamTempl(),
//qt_meta_data_eloamComLib__IEloamTempl }
};

void *IEloamTempl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamTempl()))
        return static_cast<void*>(const_cast<IEloamTempl*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__EloamVideoCap[] = {

 // content:
       1,       // revision
       0,       // classname
       1,    10, // classinfo
       13,    12, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // classinfo: key, value
       27, 39, 

 // signals: signature, parameters, type, tag, flags
       54, 93, 115, 116, 5,
       117, 142, 147, 148, 5,
       149, 175, 190, 191, 5,

 // slots: signature, parameters, type, tag, flags
       192, 202, 203, 208, 9,
       209, 241, 247, 252, 9,
       253, 303, 326, 331, 9,
       332, 351, 352, 356, 9,
       357, 373, 374, 379, 9,
       380, 424, 478, 483, 9,
       484, 512, 513, 518, 9,
       519, 601, 687, 692, 9,
       693, 709, 710, 715, 9,
       716, 731, 732, 737, 9,

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__EloamVideoCap() {
    static const char stringdata0[] = {
    "eloamComLib::EloamVideoCap\0"
    "Interface 0\0IEloamVideoCap\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Destroy()\0\0bool\0\0VideoCapAddVideoSrc(IDispatch*)\0"
    "video\0bool\0\0VideoCapAddVideoSrcEx(IDispatch*,int,int,int,int)\0video,x,y,width,heigth\0bool\0\0VideoCapGetState()\0\0int\0\0VideoCapPause()\0\0bool\0\0VideoCapPreCap(QString,int,int,int,int,int)\0fileName,micIndex,frameRate,compressMode,width,heigth\0"
    "bool\0\0VideoCapRemoveAllVideoSrc()\0\0bool\0\0VideoCapSetWatermark(int,int,int,int,int,QString,QString,int,QString,int,int,int)\0Watermark,AddTime,mode,pos,alpha,imgPath,pStrText,color,faceName,weight,height,italic\0"
    "bool\0\0VideoCapStart()\0\0bool\0\0VideoCapStop()\0\0bool\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject EloamVideoCap::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__EloamVideoCap(),
//qt_meta_data_eloamComLib__EloamVideoCap }
};

void *EloamVideoCap::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__EloamVideoCap()))
        return static_cast<void*>(const_cast<EloamVideoCap*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_eloamComLib__IEloamVideoCap[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       13,    10, // methods
       1,    75, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       28, 67, 89, 90, 5,
       91, 116, 121, 122, 5,
       123, 149, 164, 165, 5,

 // slots: signature, parameters, type, tag, flags
       166, 176, 177, 182, 9,
       183, 215, 221, 226, 9,
       227, 277, 300, 305, 9,
       306, 325, 326, 330, 9,
       331, 347, 348, 353, 9,
       354, 398, 452, 457, 9,
       458, 486, 487, 492, 9,
       493, 575, 661, 666, 9,
       667, 683, 684, 689, 9,
       690, 705, 706, 711, 9,

 // properties: name, type, flags
       712, 720, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_eloamComLib__IEloamVideoCap() {
    static const char stringdata0[] = {
    "eloamComLib::IEloamVideoCap\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "Destroy()\0\0bool\0\0VideoCapAddVideoSrc(IDispatch*)\0video\0bool\0\0VideoCapAddVideoSrcEx(IDispatch*,int,int,int,int)\0"
    "video,x,y,width,heigth\0bool\0\0VideoCapGetState()\0\0int\0\0VideoCapPause()\0\0bool\0\0VideoCapPreCap(QString,int,int,int,int,int)\0fileName,micIndex,frameRate,compressMode,width,heigth\0bool\0\0VideoCapRemoveAllVideoSrc()\0"
    "\0bool\0\0VideoCapSetWatermark(int,int,int,int,int,QString,QString,int,QString,int,int,int)\0Watermark,AddTime,mode,pos,alpha,imgPath,pStrText,color,faceName,weight,height,italic\0bool\0\0VideoCapStart()\0\0bool\0"
    "\0VideoCapStop()\0\0bool\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject IEloamVideoCap::staticMetaObject = {
//{ &QObject::staticMetaObject,
//qt_meta_stringdata_eloamComLib__IEloamVideoCap(),
//qt_meta_data_eloamComLib__IEloamVideoCap }
};

void *IEloamVideoCap::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_eloamComLib__IEloamVideoCap()))
        return static_cast<void*>(const_cast<IEloamVideoCap*>(this));
    return QAxObject::qt_metacast(_clname);
}

